export const GET_APPROVED_REQUEST = '@@calendar/GET_APPROVED_REQUEST'
export const GET_APPROVED_SUCCESS = '@@calendar/GET_APPROVED_SUCCESS'
export const GET_APPROVED_FAIL = '@@calendar/GET_APPROVED_FAIL'

export const GET_EXCLUDED_DATES_REQUEST =
  '@@calendar/GET_EXCLUDED_DATES_REQUEST'
export const GET_EXCLUDED_DATES_SUCCESS =
  '@@calendar/GET_EXCLUDED_DATES_SUCCESS'
export const GET_EXCLUDED_DATES_FAIL = '@@calendar/GET_EXCLUDED_DATES_FAIL'

export const ADD_EXCLUDED_DATE_REQUEST = '@@calendar/ADD_EXCLUDED_DATE_REQUEST'
export const ADD_EXCLUDED_DATE_SUCCESS = '@@calendar/ADD_EXCLUDED_DATE_SUCCESS'
export const ADD_EXCLUDED_DATE_FAIL = '@@calendar/ADD_EXCLUDED_DATE_FAIL'

export const DELETE_EXCLUDED_DATE_REQUEST =
  '@@calendar/DELETE_EXCLUDED_DATE_REQUEST'
export const DELETE_EXCLUDED_DATE_SUCCESS =
  '@@calendar/DELETE_EXCLUDED_DATE_SUCCESS'
export const DELETE_EXCLUDED_DATE_FAIL = '@@calendar/DELETE_EXCLUDED_DATE_FAIL'
