export const LEAVE_REQUEST_SUBMIT = '@@requests/LEAVE_REQUEST_SUBMIT'
export const LEAVE_REQUEST_SUCCESS = '@@requests/LEAVE_REQUEST_SUCCESS'
export const LEAVE_REQUEST_FAIL = '@@requests/LEAVE_REQUEST_FAIL'

export const REQUEST_USER_REQUESTS = '@@requests/REQUEST_USER_REQUESTS'
export const USER_REQUESTS_SUCCESS = '@@requests/USER_REQUESTS_SUCCESS'
export const USER_REQUESTS_FAIL = '@@requests/USER_REQUESTS_FAIL'

export const DELETE_REQUEST_SUBMIT = '@@requests/DELETE_REQUEST_SUBMIT'
export const DELETE_REQUEST_SUCCESS = '@@requests/DELETE_REQUEST_SUCCESS'
export const DELETE_REQUEST_FAIL = '@@requests/DELETE_REQUEST_FAIL'

export const SET_CURRENT_REQUEST = '@@requests/SET_CURRENT_REQUEST'
