export const PENDING_APPROVALS_REQUEST = '@@admin/PENDING_APPROVALS_REQUEST'
export const PENDING_APPROVALS_SUCCESS = '@@admin/PENDING_APPROVALS_SUCCESS'
export const PENDING_APPROVALS_FAIL = '@@admin/PENDING_APPROVALS_FAIL'
