export const PENDING_APPROVALS_REQUEST = '@@admin/PENDING_APPROVALS_REQUEST'
export const PENDING_APPROVALS_SUCCESS = '@@admin/PENDING_APPROVALS_SUCCESS'
export const PENDING_APPROVALS_FAIL = '@@admin/PENDING_APPROVALS_FAIL'

export const SET_APPROVAL_STATUS_REQUEST = '@@admin/SET_APPROVAL_STATUS_REQUEST'
export const SET_APPROVAL_STATUS_FAIL = '@@admin/SET_APPROVAL_STATUS_FAIL'
export const SET_APPROVAL_STATUS_SUCCESS = '@@admin/SET_APPROVAL_STATUS_SUCCESS'

export const QUERY_REQUESTS_REQUEST = '@@admin/QUERY_REQUESTS_REQUEST'
export const QUERY_REQUESTS_SUCCESS = '@@admin/QUERY_REQUESTS_SUCCESS'
export const QUERY_REQUESTS_FAIL = '@@admin/QUERY_REQUESTS_FAIL'
