export const REQUEST_LOGIN = '@@user/REQUEST_LOGIN'
export const USER_LOGIN_SUCCESS = '@@user/USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = '@@user/USER_LOGIN_FAIL'
export const SET_CURRENT_USER = '@@user/SET_CURRENT_USER'
export const NO_CURRENT_USER = '@@user/NO_CURRENT_USER'
export const LOG_USER_OUT = '@@user/LOG_USER_OUT'
export const REQUEST_USER = '@@user/REQUEST_USER'
